### ISSUE TITLE
Application broken when sectionsColor is missed

### ISSUE THREAD

**Issue by dynchen** [alvarotrigo/react-fullpage#144] opened 2019-07-18 03:01 UTC
When upgrade to version 0.1.15，my application is broken. I fixed it by adding `sectionsColor=[]` in props.

**Comment by alvarotrigo** [comment] 2019-07-18 10:30
Thanks for reporting it!
I was able to reproduce the issue in the [codesandbox provided in the docs](https://codesandbox.io/s/m34yq5q0qx) when removing the `sectionsColor` property.

> Error
A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.

![image](https://user-images.githubusercontent.com/1706326/61450619-c2629400-a957-11e9-8b20-443800791efd.png)

@cmswalker @adhrinae could it be because we are not making sure the property exist before dealing with it [here](https://github.com/alvarotrigo/react-fullpage/blob/master/components/ReactFullpage/index.js#L74)?

```js
    //comparing sectionColors array option
    var areSameSectionColors = true;
    this.props.sectionsColor.forEach(function(item, index) {
      areSameSectionColors =
        item === prevProps.sectionsColor[index] && areSameSectionColors;
    });
```

**Comment by adhrinae** [comment] 2019-07-22 12:17
I've found the solution and experimenting bit more elegant way to express it in codes.

**Comment by alvarotrigo** [comment] 2019-07-22 14:50
The issue has been fixed in the dev branch thanks to @adhrinae !

**Comment by alvarotrigo** [comment] 2019-08-08 10:28
Any reason why you reopened the issue @dynchen ?

**Comment by alvarotrigo** [comment] 2019-08-18 10:55
Merged now!

**Closed by alvarotrigo** 2019-08-18 10:55 UTC
Labels: bug, fixed on dev
