### ISSUE TITLE
Cannot read property 'destroy' of undefined - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 4l3nc** [alvarotrigo/react-fullpage#83] opened 2018-11-27 09:28 UTC
Hello @alvarotrigo, I'm using this library in a web project and I was in the 0.1.2 version. After the update to solve the problem with scrolloverflow I found this issue.

I did an example in _codesandbox_ because is better if you see what happened:

https://codesandbox.io/s/7mjm2z14lq

The thing is that I'm using 2 different libraries if you are on mobile or desktop. So I show one library or another depending on the width of the screen, but now with the new version, if I change to the other component and go back to the fullpage one I'm getting this error, you can check in the _codesandbox_.

If you need more details just ask 👋

**Comment by alvarotrigo** [comment] 2018-11-27 11:56
That's a [known issue](https://github.com/alvarotrigo/react-fullpage/issues/38).

I'll be releasing fullPage.js 3.0.4 this week and that should get rid of the issue. 
If you want to solve it manually just replace your `vendors/scrollOverflow.js` file for [the one in the dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js).

**Comment by alvarotrigo** [comment] 2018-11-27 11:57
I'll close this issue as it is a duplicate of #38 which stills open.

**Closed by alvarotrigo** 2018-11-27 11:57 UTC
Labels: duplicate
