### ISSUE TITLE
Initial load of this plugin inside FB / IG browser miscalculates page height, renders incorrectly

### ISSUE THREAD

**Issue by juxton** [alvarotrigo/react-fullpage#127] opened 2019-06-17 20:21 UTC
@juxton commented on [Mon Jun 17 2019](https://github.com/alvarotrigo/fullPage.js/issues/3675)

See here, with the official plugin page. You can reproduce this error by launching https://alvarotrigo.com/react-fullpage from within Facebook, for example. After the initial load (closing the in-app browser and opening it again) - rendering works correctly. This appears to be the case with both Facebook and Instagram in-app browsers. Both initially load with broken layout.

![IMG_3700](https://user-images.githubusercontent.com/4366237/59633863-509ded00-9102-11e9-800b-e851e33c7235.PNG)

**Comment by alvarotrigo** [comment] 2019-06-17 20:25
Thanks for reporting it!

Can you experience the same with the fullPage.js site?
https://alvarotrigo.com/fullPage/

**Comment by juxton** [comment] 2019-06-17 20:30
Thanks for your quick response. I accidentally opened a ticket in fullPage repo, before realizing I meant to open it here. Yes, same thing happens with /fullPage on initial load. I find the easiest way to test this is to post the link to my FB feed, and open from there. Here's initial load of /fullPage...

![IMG_3700](https://user-images.githubusercontent.com/4366237/59634523-d8d0c200-9103-11e9-957a-01970a41d1bb.PNG)

My guess is this could be some kind of race condition - because revisits seem to work correctly (after data has been cached). Just a guess, though.

**Comment by alvarotrigo** [comment] 2019-06-17 20:35
If it happens with the fullPage.js site too then the issue is in fullpage.js and not in react-fullpage. I'll close this issue and keep the one in the fullPage.js repository.

**Closed by alvarotrigo** 2019-06-17 20:35 UTC
