### ISSUE TITLE
simple <input/> not working after scroll. 

### ISSUE THREAD

**Issue by chordspear** [alvarotrigo/react-fullpage#390] opened 2023-02-13 01:33 UTC
### Description

This is likely a known issue but could not find a fix.

### Link to isolated reproduction with no external CSS / JS

Added html <input /> in each page on top of the base-example in readme. 

https://codesandbox.io/s/react-fullpage-js-example-forked-qg6vf2?file=/src/index.js

Did some debugging - 

onKeyDown event is triggered, but onChange is not. 

### Steps to reproduce it
1. scroll down to next page
2. Try writing on input field.

**Comment by chordspear** [comment] 2023-02-13 02:06
Tried with version 0.1.31 and works fine - likely an issue with the new release. (.32)

**Comment by alvarotrigo** [comment] 2023-02-13 11:04
It seems to be working for me:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/1706326/218441325-062c0d5d-7bc7-4dcf-b413-fbe93699bd86.png">

What browser and OS are you using?
What device?
Touch or mouse?
How do you

**Comment by alvarotrigo** [comment] 2023-02-13 19:39
I was able to reproduce the issue!
Thanks for reporting it! 👍 

It [has been reported on the repository for the JS library](https://github.com/alvarotrigo/fullPage.js/issues/4514) so I'll be continuing the conversation there,

**Comment by alvarotrigo** [comment] 2023-02-16 13:26
Fixed in react-fullpage 0.1.33!

**Closed by alvarotrigo** 2023-02-16 13:26 UTC
Labels: bug, fixed on dev
