### ISSUE TITLE
react-fullpage component not unmounting properly with react-router-dom

### ISSUE THREAD

**Issue by anshuraj** [alvarotrigo/react-fullpage#49] opened 2018-10-15 09:00 UTC
When switching to different route from fullpage slides, I get the following error in console and I can not scroll on the new page:
```
Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined
    at $ (react-fullpage.js:115)
    at te (react-fullpage.js:115)
    at Mt (react-fullpage.js:115)
    at Wt (react-fullpage.js:115)
    at HTMLDocument.Ft (react-fullpage.js:115)
```
Fullpage navigation appears on other routes as well.

**Comment by alvarotrigo** [comment] 2018-10-15 10:33
Are you using the latest fullpage-react version 0.1.2? 
If not, please update.
If you are, please provide an isolated reproduction in [codesandbox](https://codesandbox.io/s/m34yq5q0qx), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by anshuraj** [comment] 2018-10-15 10:43
I was using older version 0.0.6. I downgraded due to this issue #44.

**Comment by alvarotrigo** [comment] 2018-10-15 10:45
@anshuraj but do you have the issue when using 0.1.2?
That's what matters here :)

**Comment by anshuraj** [comment] 2018-10-15 12:31
No, It works fine in latest version.

**Comment by alvarotrigo** [comment] 2018-10-15 16:01
Then I'll close the issue as it was solved on the latest version. 
Issue #44 is the one that has to get fixed.

**Closed by alvarotrigo** 2018-10-15 16:01 UTC
Labels: reproduction required

**Comment by alvarotrigo** [comment] 2019-01-10 16:51
> My "Header" component, which is outside the React.Fullpage.Wrapper and is set as fixedElements, gets carried on when I navigate to another page.

There's no need to use the option `fixedElements`. All that option does is placing those elements outside the fullPage.js wrapper so browsers won't have issues when dealing with fixed elements inside elements using translate3d transformations.

Try placing them outside the fullPage.js structure and removing your `fixedElements` option.

**Comment by JalilArfaoui** [comment] 2020-01-10 16:42
I think I have the same issue here, but I can’t place my header outside the whole fullpage structure because I use some same state informations :

**Comment by JalilArfaoui** [comment] 2020-01-10 17:01
I think I have the same issue, but I can’t move my header outside the whole fullpage structure, because I use some informations from the state :

```ts
const Home: React.FC<NavProps> = ({ setPage }: NavProps) => (
  <ReactFullpage
    licenseKey="XXX"
    anchors={[
      "/welcome",
      …
    ]}
    scrollingSpeed={1000}
    fixedElements="#header"
    sectionSelector="section"
    scrollBar={false}
    scrollOverflow={true}
    scrollOverflowReset={false}
    scrollOverflowOptions={{ scrollbars: false }}
    onLeave={() => {}}
    render={({ state }) => (
      <>
        <HeaderMain
          id="header"
          isTop={
            !state.initialized ||
            !state.destination ||
            state.destination.index === 0
          }
          currentSection={
            state.destination && state.destination.anchor
              ? state.destination.anchor
              : "welcome"
          }
        />
        <ReactFullpage.Wrapper>
          <Welcome/>
          <Section2 />
           …
        </ReactFullpage.Wrapper>
      </>
    )}
  />
);
```

`<HeaderMain>` is not removed from the DOM when `ReactFullpage` is unmounted, and then it’s injected again in the DOM when `ReactFullpage` mounted, thus generating duplicated nodes :

![image](https://user-images.githubusercontent.com/3037833/72171225-dc46d600-33d2-11ea-97c1-478358b3231c.png)

I’m using version 0.1.17.

**Comment by alvarotrigo** [comment] 2020-01-11 01:52
@JalilArfaoui you'll have to find the way to place your header outside the fullpage wrapper.  
Fixed elements can not be inside elements suffering from `translate3d` transformations.

**Comment by froii** [comment] 2020-11-25 10:23
@alvarotrigo  But how i can use fullpageApi moveSectionDown outside ? if i create arrow next, previous and dependence things ?

**Comment by alvarotrigo** [comment] 2020-11-25 10:45
You can use `fullpage_api` which lives int he window object.

**Comment by S4hk** [comment] 2023-01-29 17:51
i cannot fully destroy it  so i resolved this  in function component by these lines 

  useEffect(() => {
    return () => {
      if (document) {
        window.fullpage_api.destroy("all");
        document.getElementById("root").style.height = "";
      }
    };
  }, []);

**Comment by alvarotrigo** [comment] 2023-01-29 21:36
Good to know! ;)
