### ISSUE TITLE
Error in vscode terminal file:Error: no such file or directory

### ISSUE THREAD

**Issue by starzje** [alvarotrigo/react-fullpage#353] opened 2022-09-19 23:56 UTC
I'm trying to set up fullPage.js with react, 

and I just did npm install:
 npm install @fullpage/react-fullpage

And when I try anything I'm getting these errors in vscode terminal:

WARNING in ./node_modules/@fullpage/react-fullpage/dist/react-fullpage.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\istar\Desktop\fullpagereact-main\node_modules\@fullpage\react-fullpage\dist\easings.min.js.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\istar\Desktop\fullpagereact-main\node_modules\@fullpage\react-fullpage\dist\easings.min.js.map'

Not sure how to work this out?

**Comment by alvarotrigo** [comment] 2022-09-20 10:35
It's a warning, not an error. So you can actually ignore it.

I'll close this issue as it's a duplicate of [this other issue](https://github.com/alvarotrigo/react-fullpage/issues/344).

**Closed by alvarotrigo** 2022-09-20 10:35 UTC
