### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by taiyrbegeyev** [alvarotrigo/react-fullpage#147] opened 2019-07-27 11:50 UTC
### Description

Every time I try to run the application it fails. It throws the following error:
```
TypeError: Cannot read property 'forEach' of undefined
```

### Link to isolated reproduction with no external CSS / JS

![Screenshot 2019-07-27 at 13 48 09](https://user-images.githubusercontent.com/44882080/61994020-6691bc80-b075-11e9-8b2c-ad5a6b275140.png)

### Steps to reproduce it
1. install react-fullpage
2. run the code snippet from README
```
import React from 'react';
import ReactDOM from 'react-dom';
import ReactFullpage from '@fullpage/react-fullpage';

const Fullpage = () => (
  <ReactFullpage
    //fullpage options
    licenseKey = {'YOUR_KEY_HERE'}
    scrollingSpeed = {1000} /* Options here */

    render={({ state, fullpageApi }) => {
      return (
        <ReactFullpage.Wrapper>
          <div className="section">
            <p>Section 1 (welcome to fullpage.js)</p>
            <button onClick={() => fullpageApi.moveSectionDown()}>
              Click me to move down
            </button>
          </div>
          <div className="section">
            <p>Section 2</p>
          </div>
        </ReactFullpage.Wrapper>
      );
    }}
  />
);

ReactDOM.render(<Fullpage />, document.getElementById('react-root'));
```
3. get the issue

### Versions 
[Browser, operating system, device, ...]
1. all browsers
2. all operatins systems

**Comment by alvarotrigo** [comment] 2019-07-29 11:54
Thanks for reporting it!

This issue has been fixed days ago thanks to @adhrinae in [this pull request](https://github.com/alvarotrigo/react-fullpage/pull/145).

If you install the development version you should be fine :)

If you prefer to wait until the next release, just make sure to add the `sectionsColor` option in the initialization. Even if it is an empty array, for example:

```js

const Fullpage = () => (
  <ReactFullpage
    //fullpage options
    licenseKey = {'YOUR_KEY_HERE'}
    scrollingSpeed = {1000} /* Options here */
    sectionsColor= {[]} /* <---- here */

    render={({ state, fullpageApi }) => {
      return (
        <ReactFullpage.Wrapper>
          <div className="section">
            <p>Section 1 (welcome to fullpage.js)</p>
            <button onClick={() => fullpageApi.moveSectionDown()}>
              Click me to move down
            </button>
          </div>
          <div className="section">
            <p>Section 2</p>
          </div>
        </ReactFullpage.Wrapper>
      );
    }}
  />
);
```

**Comment by leohxj** [comment] 2019-08-18 09:45
why not publish a patch to hotfix this?

**Comment by alvarotrigo** [comment] 2019-08-18 09:56
> why not publish a patch to hotfix this?

The issue is closed and marked as "fixed". 
Which means the issue was fixed back then and you won't experience it in the latest version anymore ;)

**Comment by leohxj** [comment] 2019-08-18 10:08
> > why not publish a patch to hotfix this?
> 
> The issue is closed and marked as "fixed".
> Which means the issue was fixed back then and you won't experience it in the latest version anymore ;)

I am useing version 0.1.15, it's the lasest version of `@fullpage/react-fullpage` right? But I still found this bug.

```bash
"@fullpage/react-fullpage@^0.1.13":
  version "0.1.15"
  resolved "https://registry.yarnpkg.com/@fullpage/react-fullpage/-/react-fullpage-0.1.15.tgz#bd31218d5556ddcbd2a554a11b3961cc781a5938"
  integrity sha512-gWZQtNimCo27F8qUUCbT2RCSKBkGNbEPoe9JlPchRywCKpypSt43UF6izJ9kUCARysX/vAYzELt6prqjv57M4g==
  dependencies:
    "@babel/polyfill" "^7.2.5"
    fullpage.js "^3.0.7"
```


> "If you install the development version you should be fine :)", 

which one is the development version? I didn't see any tag of development.

Thanks.

**Comment by alvarotrigo** [comment] 2019-08-18 10:55
Oh wow! I have no idea why but I though I merged it!
Thanks for the heads up! 👍 

I've just created a new release 0.1.16 that fixes the issue!

**Closed by alvarotrigo** 2019-08-18 10:55 UTC
Labels: bug, fixed on dev
